language:
  - ruby
before_script:
  - psql -c 'create database hot_streak_client_test;' -U postgres
rvm:
  - "2.2.0"
addons:
  code_climate:
    repo_token: a647046c4a71eeeb18c103f066db4e427c4c39a8bf28f565d8f2905ad58e3ce1

notifications:
  email: false
