default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: committen_rails_development

test:
  <<: *default
  database: committen_rails_test

production:
  <<: *default
  database: committen_rails_production
