default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hot_streak_client_development

test:
  <<: *default
  database: hot_streak_client_test

production:
  <<: *default
  database: hot_streak_client_production
